---
- name: Install database packages
  apt: pkg={{ item }} force=yes install_recommends=no update_cache=yes state=present
  with_items:
    - postgresql-9.5
    - postgresql-client-9.5
    - python-psycopg2

- name: Create database user
  user: name={{ database_user }}

- name: Create database
  postgresql_db: name={{ database_name }}
                 encoding=UTF8
  become: true
  become_user: postgres

- name: Create local database user
  postgresql_user: db={{ database_name }} name={{ database_user }}
                   role_attr_flags=SUPERUSER
  become: true
  become_user: postgres

...
