- hosts: default
  become: yes
  become_method: sudo
  gather_facts: False
  roles:
    - base
    - database
    - webserver

  vars:
    environ: local
    public_dns: localhost
    DEBUG: "True"
    SECRET_KEY: foobar
    DATABASE_PASSWORD: none
    DATABASE_HOST: none
    IAM_USER_ACCESS_KEY_ID: none
    IAM_USER_SECRET_ACCESS_KEY: none
