- hosts: default
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
    - base
    - database
    - webserver

  vars:
    environ: local
    public_dns: localhost
    DEBUG: "True"
    SECRET_KEY: foobar
    DATABASE_PASSWORD: ''
    DATABASE_HOST: ''
    IAM_USER_ACCESS_KEY_ID: ''
    IAM_USER_SECRET_ACCESS_KEY: ''
    APP_EMAIL_USER: ''
    APP_EMAIL_PASSWORD: ''
