---
- name: Install pre-reqs
  apt: name=software-properties-common
       update_cache=yes

- name: Add Certbot repo
  apt_repository: repo=ppa:certbot/certbot
                  update_cache=yes

- name: Install Certbot
  apt: name=python-certbot-nginx
       update_cache=yes

...
